name: proyecto_netflix
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (BASE)
  firebase_core: ^2.32.0

  # Auth (login / register)
  firebase_auth: ^4.19.0

  # Firestore (usuarios)
  cloud_firestore: ^4.17.5

  # Realtime Database (pelÃ­culas)
  firebase_database: ^10.5.7

  # Storage (trailers)
  firebase_storage: ^11.7.7

  # Video player
  image_picker: ^1.2.1
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2
  video_player: ^2.8.1
  chewie: ^1.8.5
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
